### ISSUE TITLE
Integrate new Plate Tectonics model in WISE embedded component

### ISSUE THREAD

**Issue by breity** [WISE-Community/plate-tectonics-boundary-explorer#2]
- Model repo: https://github.com/davidchuyaya/plate-tectonics
- Add to Kelly's PT unit as embedded component: https://wise.berkeley.edu/preview/unit/33873/node263
- Save and repopulate student data in WISE:
  - Object for each location:
    - Location data (name, images?, boundary type?)
    - Array of attempts (each attempt includes boundary type selection, convergent vs divergent selection, prediction text, correct or incorrect)
    - Completion status
  - Repopulate each location with latest attempt
  - Repopulate map view with completed locations

Deadline: Feb 3, 2021 (runs start Feb 8)

**Comment by hirokiterashima** [comment]
Implemented in 189546418886661a9757f8e4db77391aeaccd13e and ce2c828418dd85c4e7f1cb5ddcdc993534f8859b
